project:
  type: website

website:
  title: "Alex Antonison's Blog"
  navbar:
    right:
      - talks.qmd
      - about.qmd
      - icon: github
        href: https://github.com/alex-antonison
      - icon: twitter
        href: https://twitter.com/adantonison
format:
  html:
    theme: superhero
    css: styles.css



