project:
  type: website

website:
  title: "Alex Antonison's Blog"
  page-footer:
    center:
      - icon: linkedin
        href: https://www.linkedin.com/in/alexantonison/
      - icon: github
        href: https://github.com/alex-antonison
  navbar:
    title: false
    left:
      - text: "Blog"
        href: index.qmd
      - text: Talks
        file: talks.qmd
      - text: Resources
        file: resources.qmd
      - text: Projects
        file: projects.qmd
      - text: Resume
        file: resume.qmd
    right:
      - icon: github
        href: https://github.com/alex-antonison
      - icon: linkedin
        href: https://www.linkedin.com/in/alexantonison/
  site-url: "https://www.alex-antonison.com/"
  repo-url: https://github.com/alex-antonison/blog
  repo-branch: main

format:
  html:
    theme: superhero
    css: styles.css



