---
title: "Resources"
talks:
  template: solana
format:
  html:
    toc: true
    toc-location: left
    toc-title: Table of Contents
---

### Overview

This is a list of resources that I keep in mind when building data platforms. I also include some day-to-day tools I use to help manage projects, time, and communication.

### Development

Development tools I use when building data solutions.

| Development Tools                                                                   | Description                                                                                                                                                                                                                                                                                      |
|------------------|------------------------------------------------------|
| <a href="https://code.visualstudio.com/" target="_blank">Visual Studio Code</a>     | A code editor that supports a wide variety of languages and uses-cases with extensions                                                                                                                                                                                                           |
| <a href="https://colab.research.google.com/" target="_blank">Google Colab</a>       | Hosted jupyter notebooks for running python. Has access to GPU/TPU if you want to explore ML.                                                                                                                                                                                                    |
| <a href="https://github.com/tmux/tmux" target="_blank">tmux</a>                     | A terminal utility to allows running command line commands server-side.                                                                                                                                                                                                                          |
| <a href="https://www.docker.com/" target="_blank">Docker</a>                        | Package software code with a complete environment.                                                                                                                                                                                                                                               |
| <a href="https://www.serverless.com/" target="_blank">Serverless</a>                | Utility that streamlines deploying serverless applications in cloud platforms such as AWS.                                                                                                                                                                                                       |
| <a href="https://cdkworkshop.com/30-python.html" target="_blank">AWS Python CDK</a> | Python Cloud Development Kit (CDK) allows for deploying AWS infrastructure using Python code.                                                                                                                                                                                                    |
| <a href="https://www.getdbt.com/" target="_blank">data build tool(dbt)</a>          | Utility that supports for creating ELT data pipelines run within a database. Used for normalizing data into a data warehouse and curating data marts. Supports data testing. Auto-generated documentation allows for making it easy to understand how data is flowing through the data platform. |
| <a href="https://github.com/" target="_blank">GitHub</a>                            | Source control platform of choice.                                                                                                                                                                                                                                                               |
| <a href="https://github.com/features/actions" target="_blank">GitHub Actions</a>    | Supports Continuous Integration/Continuous Deployment (CI/CD)                                                                                                                                                                                                                                    |
| <a href="https://dbeaver.io/" target="_blank">dbeaver</a>                           | Tool for interacting with SQL databases                                                                                                                                                                                                                                                          |
| <a href="https://pre-commit.com/" target="_blank">pre-commit</a>                    | pre-commit is a tool that can run a series of checks when committing files to a git based source control                                                                                                                                                                                         |

### Programming Languages

Programming languages I consider when building data platforms, doing statistical analysis, machine learning, etc.

| Language                                                              | Purpose                                                                                                                     |
|--------------------------|---------------------------------------------|
| <a href="https://www.python.org/" target="_blank">Python</a>          | A general usage language that supports building data platforms, data analytics, statistical analysis, and machine learning. |
| <a href="https://www.r-project.org/about.html" target="_blank">R</a>  | A language built for performing statistical analysis, machine learning, and data analysis.                                  |
| <a href="https://julialang.org/" target="_blank">Julia</a>            | A high performant language for scientific computing.                                                                        |
| <a href="https://www.scala-lang.org/" target="_blank">Scala</a>       | For writing performant Spark data applications.                                                                             |
| <a href="https://go.dev/" target="_blank">Go</a>                      | Building efficient data microservices.                                                                                      |
| <a href="https://www.w3schools.com/sql/" target="_blank">SQL</a>      | Structured query language for pulling data from relational databases.                                                       |
| <a href="https://www.gnu.org/software/bash/" target="_blank">bash</a> | A shell scripting language that can be helpful in automating tasks.                                                         |

### Python Development Tools

| Tool                                                                                           | Type                   | Purpose                                                                                                           |
|--------------------------|---------------|-------------------------------|
| <a href="https://black.readthedocs.io/en/stable/" target="_blank">black</a>                    | Clean Code             | black is a python code formatter that helps keep code consistently formatted across teams                         |
| <a href="https://pycqa.github.io/isort/" target="_blank">isort</a>                             | Clean Code             | isort helps organize python imports                                                                               |
| <a href="https://flake8.pycqa.org/en/latest/" target="_blank">flake8</a>                       | Clean Code             | flake8 is a code linter that enforces coding styles such as flagging unused imports                               |
| <a href="http://mypy-lang.org/" target="_blank">mypy</a>                                       | Clean Code             | mypy is a static type checker that helps solve the problem in python with dynamic typing                          |
| <a href="https://docs.pytest.org/" target="_blank">pytest</a>                                  | Testing                | pytest is my unit testing tool of choice for it's extensibility for building test harnesses                       |
| <a href="https://greatexpectations.io/" target="_blank">great-expectations</a>                 | Testing                | Supports data quality testing and validation                                                                      |
| <a href="https://tdda.readthedocs.io/en/latest/" target="_blank">Test-Driven Data Analysis</a> | Testing                | A package that supports integrating data quality tests with unit tests such as pytest                             |
| <a href="https://python-poetry.org/" target="_blank">poetry</a>                                | Environment Management | A python package that supports managing virtual environments                                                      |
| <a href="https://dvc.org/" target="_blank">data version control(dvc)</a>                       | ML Ops                 | Utility that provides a streamlined approach for managing machine learning models from development to production. |
| <a href="https://aws-sdk-pandas.readthedocs.io/en/stable/" target="_blank">awswrangler</a>     | AWS SDK                | AWS Development                                                                                                   |

### Favorite Python Analysis Tools

| Tool                                                                                   | Type                           | Purpose                                                                                                                   |
|-----------------------|----------------|---------------------------------|
| <a href="https://jupyter.org/" target="_blank">jupyter notebooks</a>                   | Analysis Tool                  | Jupyter notebooks allow for running python in a cell format and being able to immediately see the results                 |
| <a href="https://spark.apache.org/docs/latest/api/python/" target="_blank">PySpark</a> | Data Processing                | Provides a Python interface to creating Spark applications                                                                |
| <a href="https://pandas.pydata.org/" target="_blank">pandas</a>                        | Dataframe                      | pandas allows for importing data into a tabular data structure and can perform cleaning and analysis activities in python |
| <a href="https://scipy.org/" target="_blank">scipy</a>                                 | Calculations                   | Python package for scientific computing                                                                                   |
| <a href="https://numpy.org/" target="_blank">numpy</a>                                 | Calculations                   | Python package for mathematical computing                                                                                 |
| <a href="https://streamlit.io/" target="_blank">streamlit</a>                          | Interactive Data Visualization | Streamlined method for creating interactive dashboards in python                                                          |
| <a href="https://plotly.com/python/" target="_blank">plotly</a>                        | Interactive Data Visualization | Streamlined method for creating interactive visualizations in python                                                      |
| <a href="https://plotnine.readthedocs.io/en/stable/" target="_blank">plotnine</a>      | Static Data Visualization      | Allows the creation of ggplot visualizations in python                                                                    |
| <a href="https://scikit-learn.org/stable/" target="_blank">scikit-learn</a>            | Machine Learning               | Machine learning in python                                                                                                |
| <a href="https://keras.io/" target="_blank">keras</a>                                  | Deep Learning                  | A high level deep learning library for creating deep learning models                                                      |

### R Development Tools

| Tool                                                                                 | Type                   | Purpose                                                                                  |
|----------------------------|---------------|-----------------------------|
| <a href="https://rstudio.github.io/renv/articles/renv.html" target="_blank">renv</a> | Environment Management | A tool for managing R packages used for a project.                                       |
| <a href="https://posit.co/" target="_blank">RStudio</a>                              | IDE                    | A IDE tailored to running R code. It can also run Python but I have not tested this out. |

### R Analysis Tools

| Tool                                                               | Type                  | Purpose                                                                                      |
|------------------------|----------------|---------------------------------|
| <a href="https://www.tidyverse.org/" target="_blank">tidyverse</a> | Analysis              | An ecosystem of r-packages that support doing a wide variety of data science/analytics tasks |
| <a href="https://shiny.rstudio.com/" target="_blank">r-shiny</a>   | Interactive Dashboard | A framework for creating interactive dashboard sites with R.                                 |

### IT Tools

This section includes a wide variety of tools and platforms used to help build and deploy data platforms.

| Item                                                                                                  | Purpose                                                                                                                                                              |
|----------------------------|--------------------------------------------|
| <a href="https://www.nomachine.com/" target="_blank">nomachine</a>                                    | Tool for remotely connecting to Linux desktop.                                                                                                                       |
| <a href="https://www.vmware.com/products/workstation-pro.html" target="_blank">VMWare Workstation</a> | Virtual Machine for running a Windows VM on a Linux computer.                                                                                                        |
| <a href="https://aws.amazon.com/" target="_blank">Amazon Web Services</a>                             | Cloud computing platform of choice for building and deploy data solutions.                                                                                           |
| <a href="https://quarto.org/" target="_blank">Quarto</a>                                              | Used for blog website.                                                                                                                                               |
| <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>                                  | For serving up personal blog site.                                                                                                                                   |
| <a href="https://domains.google/" target="_blank">Google Domains</a>                                  | Used for custom domains                                                                                                                                              |
| <a href="https://www.squarespace.com/" target="_blank">Squarespace</a>                                | Website builder for managing business website.                                                                                                                       |
| <a href="https://draw.io/" target="_blank">draw.io</a>                                                | Free tool for creating ERD diagrams, process flows, and AWS Architectures                                                                                            |
| <a href="https://www.juiceanalytics.com/" target="_blank">Juicebox Analytics</a>                      | Data Storytelling tool                                                                                                                                               |
| <a href="https://www.markdownguide.org/getting-started/" target="_blank">Markdown</a>                 | Markup language for writing documentation.                                                                                                                           |
| <a href="https://github.com/ohmybash/oh-my-bash" target="_blank">oh-my-bash</a>                       | Framework for managing bash configuration. There is also a zshell equivalent, <a href="https://github.com/ohmyzsh/ohmyzsh" target="_blank">oh-my-zsh</a> equivalent. |
| <a href="https://cookiecutter.readthedocs.io/en/stable/" target="_blank">Cookiecutter</a>             | A project templating tool.                                                                                                                                           |

### Visual Studio Code Extensions

Visual Studio Code Extensions I find useful.

| Visual Studio Code Extension                                                                                                                        |
|------------------------------------------------------------------------|
| <a href="https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github" target="_blank">GitHub Pull Requests and Issues</a> |
| <a href="https://marketplace.visualstudio.com/items?itemName=ms-python.python" target="_blank">Python</a>                                           |
| <a href="https://marketplace.visualstudio.com/items?itemName=quarto.quarto" target="_blank">Quarto</a>                                              |
| <a href="https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint" target="_blank">markdownlint</a>                       |
| <a href="https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager" target="_blank">Project Manager</a>                       |
| <a href="https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack" target="_blank">Remote Development</a>   |
| <a href="https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker" target="_blank">Code Spell Checker</a>          |
| <a href="https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker" target="_blank">Docker</a>                                |
| <a href="https://marketplace.visualstudio.com/items?itemName=janisdd.vscode-edit-csv" target="_blank">Edit csv</a>                                  |

### Productivity and General Use

Productivity tools and general use programs.

| Item                                                                         | Purpose                                                                                                                                                                       |
|-----------------------|-------------------------------------------------|
| <a href="https://trello.com/" target="_blank">Trello</a>                     | Productivity tool used for planning out work                                                                                                                                  |
| <a href="https://workspace.google.com/" target="_blank">Google Workspace</a> | Frequently use Google Docs and Google Sheets                                                                                                                                  |
| <a href="https://brave.com/" target="_blank">Brave</a>                       | A privacy first browser built on Chrome                                                                                                                                       |
| <a href="https://www.mozilla.org/en-US/firefox/" target="_blank">Firefox</a> | Firefox has a [Multi-Account Container](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) supports logging into multiple accounts in a single Window. |
| <a href="https://calendly.com/" target="_blank">Calendly</a>                 | Website to streamline scheduling meetings.                                                                                                                                    |
| <a href="https://feedly.com/" target="_blank">Feedly</a>                     | RSS Feed Tool that has a good free tier.                                                                                                                                      |
| <a href="https://zoom.us/" target="_blank">zoom</a>                          | Video Conferencing tool of choice.                                                                                                                                            |
